/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DisputePolicyRouteImport } from './routes/dispute-policy'
import { Route as ForBuyersRouteImport } from './routes/for-buyers'
import { Route as ForSellersRouteImport } from './routes/for-sellers'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as WaitlistConfirmRouteImport } from './routes/waitlist.confirm'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin.login'
import { Route as ApiAdminWaitlistRouteImport } from './routes/api.admin.waitlist'
import { Route as ApiAdminWaitlistIdRouteImport } from './routes/api.admin.waitlist.$id'
import { Route as ApiAdminWaitlistIdFlagRouteImport } from './routes/api.admin.waitlist.$id.flag'
import { Route as ApiAdminWaitlistIdPointsRouteImport } from './routes/api.admin.waitlist.$id.points'
import { Route as ApiAdminWaitlistIdVerifiedRouteImport } from './routes/api.admin.waitlist.$id.verified'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputePolicyRoute = DisputePolicyRouteImport.update({
  id: '/dispute-policy',
  path: '/dispute-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBuyersRoute = ForBuyersRouteImport.update({
  id: '/for-buyers',
  path: '/for-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSellersRoute = ForSellersRouteImport.update({
  id: '/for-sellers',
  path: '/for-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/admin/waitlist',
  path: '/admin/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistConfirmRoute = WaitlistConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => WaitlistRoute,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWaitlistRoute = ApiAdminWaitlistRouteImport.update({
  id: '/api/admin/waitlist',
  path: '/api/admin/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWaitlistIdRoute = ApiAdminWaitlistIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminWaitlistRoute,
} as any)
const ApiAdminWaitlistIdFlagRoute = ApiAdminWaitlistIdFlagRouteImport.update({
  id: '/flag',
  path: '/flag',
  getParentRoute: () => ApiAdminWaitlistIdRoute,
} as any)
const ApiAdminWaitlistIdPointsRoute =
  ApiAdminWaitlistIdPointsRouteImport.update({
    id: '/points',
    path: '/points',
    getParentRoute: () => ApiAdminWaitlistIdRoute,
  } as any)
const ApiAdminWaitlistIdVerifiedRoute =
  ApiAdminWaitlistIdVerifiedRouteImport.update({
    id: '/verified',
    path: '/verified',
    getParentRoute: () => ApiAdminWaitlistIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dispute-policy': typeof DisputePolicyRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-sellers': typeof ForSellersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/waitlist/confirm': typeof WaitlistConfirmRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/waitlist': typeof ApiAdminWaitlistRouteWithChildren
  '/api/admin/waitlist/$id': typeof ApiAdminWaitlistIdRouteWithChildren
  '/api/admin/waitlist/$id/flag': typeof ApiAdminWaitlistIdFlagRoute
  '/api/admin/waitlist/$id/points': typeof ApiAdminWaitlistIdPointsRoute
  '/api/admin/waitlist/$id/verified': typeof ApiAdminWaitlistIdVerifiedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dispute-policy': typeof DisputePolicyRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-sellers': typeof ForSellersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/waitlist/confirm': typeof WaitlistConfirmRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/waitlist': typeof ApiAdminWaitlistRouteWithChildren
  '/api/admin/waitlist/$id': typeof ApiAdminWaitlistIdRouteWithChildren
  '/api/admin/waitlist/$id/flag': typeof ApiAdminWaitlistIdFlagRoute
  '/api/admin/waitlist/$id/points': typeof ApiAdminWaitlistIdPointsRoute
  '/api/admin/waitlist/$id/verified': typeof ApiAdminWaitlistIdVerifiedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dispute-policy': typeof DisputePolicyRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-sellers': typeof ForSellersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/waitlist/confirm': typeof WaitlistConfirmRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/waitlist': typeof ApiAdminWaitlistRouteWithChildren
  '/api/admin/waitlist/$id': typeof ApiAdminWaitlistIdRouteWithChildren
  '/api/admin/waitlist/$id/flag': typeof ApiAdminWaitlistIdFlagRoute
  '/api/admin/waitlist/$id/points': typeof ApiAdminWaitlistIdPointsRoute
  '/api/admin/waitlist/$id/verified': typeof ApiAdminWaitlistIdVerifiedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dispute-policy'
    | '/for-buyers'
    | '/for-sellers'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/waitlist'
    | '/admin/waitlist'
    | '/waitlist/confirm'
    | '/api/admin/login'
    | '/api/admin/waitlist'
    | '/api/admin/waitlist/$id'
    | '/api/admin/waitlist/$id/flag'
    | '/api/admin/waitlist/$id/points'
    | '/api/admin/waitlist/$id/verified'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dispute-policy'
    | '/for-buyers'
    | '/for-sellers'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/waitlist'
    | '/admin/waitlist'
    | '/waitlist/confirm'
    | '/api/admin/login'
    | '/api/admin/waitlist'
    | '/api/admin/waitlist/$id'
    | '/api/admin/waitlist/$id/flag'
    | '/api/admin/waitlist/$id/points'
    | '/api/admin/waitlist/$id/verified'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dispute-policy'
    | '/for-buyers'
    | '/for-sellers'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/waitlist'
    | '/admin/waitlist'
    | '/waitlist/confirm'
    | '/api/admin/login'
    | '/api/admin/waitlist'
    | '/api/admin/waitlist/$id'
    | '/api/admin/waitlist/$id/flag'
    | '/api/admin/waitlist/$id/points'
    | '/api/admin/waitlist/$id/verified'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DisputePolicyRoute: typeof DisputePolicyRoute
  ForBuyersRoute: typeof ForBuyersRoute
  ForSellersRoute: typeof ForSellersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WaitlistRoute: typeof WaitlistRouteWithChildren
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminWaitlistRoute: typeof ApiAdminWaitlistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispute-policy': {
      id: '/dispute-policy'
      path: '/dispute-policy'
      fullPath: '/dispute-policy'
      preLoaderRoute: typeof DisputePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-buyers': {
      id: '/for-buyers'
      path: '/for-buyers'
      fullPath: '/for-buyers'
      preLoaderRoute: typeof ForBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-sellers': {
      id: '/for-sellers'
      path: '/for-sellers'
      fullPath: '/for-sellers'
      preLoaderRoute: typeof ForSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/admin/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/confirm': {
      id: '/waitlist/confirm'
      path: '/confirm'
      fullPath: '/waitlist/confirm'
      preLoaderRoute: typeof WaitlistConfirmRouteImport
      parentRoute: typeof WaitlistRoute
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/waitlist': {
      id: '/api/admin/waitlist'
      path: '/api/admin/waitlist'
      fullPath: '/api/admin/waitlist'
      preLoaderRoute: typeof ApiAdminWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/waitlist/$id': {
      id: '/api/admin/waitlist/$id'
      path: '/$id'
      fullPath: '/api/admin/waitlist/$id'
      preLoaderRoute: typeof ApiAdminWaitlistIdRouteImport
      parentRoute: typeof ApiAdminWaitlistRoute
    }
    '/api/admin/waitlist/$id/flag': {
      id: '/api/admin/waitlist/$id/flag'
      path: '/flag'
      fullPath: '/api/admin/waitlist/$id/flag'
      preLoaderRoute: typeof ApiAdminWaitlistIdFlagRouteImport
      parentRoute: typeof ApiAdminWaitlistIdRoute
    }
    '/api/admin/waitlist/$id/points': {
      id: '/api/admin/waitlist/$id/points'
      path: '/points'
      fullPath: '/api/admin/waitlist/$id/points'
      preLoaderRoute: typeof ApiAdminWaitlistIdPointsRouteImport
      parentRoute: typeof ApiAdminWaitlistIdRoute
    }
    '/api/admin/waitlist/$id/verified': {
      id: '/api/admin/waitlist/$id/verified'
      path: '/verified'
      fullPath: '/api/admin/waitlist/$id/verified'
      preLoaderRoute: typeof ApiAdminWaitlistIdVerifiedRouteImport
      parentRoute: typeof ApiAdminWaitlistIdRoute
    }
  }
}

interface WaitlistRouteChildren {
  WaitlistConfirmRoute: typeof WaitlistConfirmRoute
}

const WaitlistRouteChildren: WaitlistRouteChildren = {
  WaitlistConfirmRoute: WaitlistConfirmRoute,
}

const WaitlistRouteWithChildren = WaitlistRoute._addFileChildren(
  WaitlistRouteChildren,
)

interface ApiAdminWaitlistIdRouteChildren {
  ApiAdminWaitlistIdFlagRoute: typeof ApiAdminWaitlistIdFlagRoute
  ApiAdminWaitlistIdPointsRoute: typeof ApiAdminWaitlistIdPointsRoute
  ApiAdminWaitlistIdVerifiedRoute: typeof ApiAdminWaitlistIdVerifiedRoute
}

const ApiAdminWaitlistIdRouteChildren: ApiAdminWaitlistIdRouteChildren = {
  ApiAdminWaitlistIdFlagRoute: ApiAdminWaitlistIdFlagRoute,
  ApiAdminWaitlistIdPointsRoute: ApiAdminWaitlistIdPointsRoute,
  ApiAdminWaitlistIdVerifiedRoute: ApiAdminWaitlistIdVerifiedRoute,
}

const ApiAdminWaitlistIdRouteWithChildren =
  ApiAdminWaitlistIdRoute._addFileChildren(ApiAdminWaitlistIdRouteChildren)

interface ApiAdminWaitlistRouteChildren {
  ApiAdminWaitlistIdRoute: typeof ApiAdminWaitlistIdRouteWithChildren
}

const ApiAdminWaitlistRouteChildren: ApiAdminWaitlistRouteChildren = {
  ApiAdminWaitlistIdRoute: ApiAdminWaitlistIdRouteWithChildren,
}

const ApiAdminWaitlistRouteWithChildren =
  ApiAdminWaitlistRoute._addFileChildren(ApiAdminWaitlistRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DisputePolicyRoute: DisputePolicyRoute,
  ForBuyersRoute: ForBuyersRoute,
  ForSellersRoute: ForSellersRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WaitlistRoute: WaitlistRouteWithChildren,
  AdminWaitlistRoute: AdminWaitlistRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminWaitlistRoute: ApiAdminWaitlistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
